### ISSUE TITLE
vite: error: require is not defined: due to temp-dir being v2

### ISSUE THREAD

**Issue by btakita** [sindresorhus/tempfile#17]
```
error   require is not defined
  File:
    /home/brian/work/portfoliome/censible-core/apps/mi-www/@fs/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/temp-dir@2.0.0/node_modules/temp-dir/index.js:4:12
  Stacktrace:
ReferenceError: require is not defined
    at eval (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/temp-dir@2.0.0/node_modules/temp-dir/index.js:4:12)
    at instantiateModule (file:///home/brian/work/portfoliome/censible-core/node_modules/.pnpm/vite@4.1.1/node_modules/vite/dist/node/chunks/dep-3007b26d.js:52400:15)
```

I noticed that temp-dir v3 supports ESM. Looks like an upgrade is needed.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/tempfile/releases/tag/v5.0.0
